/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Insumos: () => import('#controllers/insumos_controller'),
  Kits: () => import('#controllers/kits_controller'),
  MagicLink: () => import('#controllers/magic_link_controller'),
  ModulosSalud: () => import('#controllers/modulos_salud_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  Skus: () => import('#controllers/skus_controller'),
  Usuarios: () => import('#controllers/usuarios_controller'),
  Zonas: () => import('#controllers/zonas_controller'),
}
